app_book:
    resource: "@AppBundle/Controller/BookController.php"
    type:     annotation

hello:
    resource: "@HelloBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
