app_hello_homepage:
 pattern: /hello/{name}
 defaults: { _controller: AppBundle:Default:hello }

app_hello_hellopage:
 pattern: /hello/{name}/{sex}
 defaults: { _controller: AppBundle:Default:index, sex: h }
 requirements:
  sex: h|f

app_hello_bookpage:
   pattern: /book/create
   defaults: { _controller: AppBundle:Default:create }

app_hello_showbookpage:
   pattern: /book/show/{id}
   defaults: { _controller: AppBundle:Default:show }

app_hello_updatebookpage:
    pattern: /book/update/{id}
    defaults: { _controller: AppBundle:Default:update }

app_hello_removebookpage:
    pattern: /book/remove/{id}
    defaults: { _controller: AppBundle:Default:remove }

app_hello_createuserpage:
    pattern: /book/createUser
    defaults: { _controller: AppBundle:Default:createUser }

app_hello_loanpage:
    pattern: /book/loan/{userId}/{bookId}
    defaults: { _controller: AppBundle:Default:loan }